# Generated by Django 5.1.5 on 2025-01-30 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusivevenues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='score',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('alt', models.CharField(max_length=100)),
                ('src', models.ImageField(upload_to='')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inclusivevenues.venue')),
            ],
        ),
    ]
