# Generated by Django 5.1.5 on 2025-02-01 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusivevenues', '0002_venue_score_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inclusivevenues.venue'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
