# Generated by Django 5.1.5 on 2025-02-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusivevenues', '0003_alter_image_venue_alter_venue_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='map',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
