# Generated by Django 5.1.5 on 2025-02-11 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusivevenues', '0004_venue_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='inclusivevenues.ratingcategory'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='inclusivevenues.review'),
        ),
    ]
