# Generated by Django 5.1.5 on 2025-02-19 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusivevenues', '0005_alter_rating_category_alter_rating_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('category', 'review'), name='unique_category_review', violation_error_message='You may only rate each category once per review'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('author', 'venue'), name='unique_venue_author', violation_error_message='You may only leave one review per venue'),
        ),
    ]
