# Generated by Django 5.1.5 on 2025-02-20 17:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusivevenues', '0006_rating_unique_category_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('5'))]),
        ),
    ]
