# Generated by Django 5.1.6 on 2025-03-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusivevenues', '0007_alter_venue_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Last modified'),
        ),
    ]
