# Generated by Django 5.2 on 2025-05-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusivevenues', '0008_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingcategory',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='venuecategory',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='venuesubcategory',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
