name: Build Django

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Move license file
        run: mv LICENSE django/LICENSE
      - name: Install build
        run: pip install build
      - name: Build Django app
        run: |
          cd django
          python -m build -w
      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: django/inclusivevenues-1.0.1-py3-none-any.whl
